// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"time"

	"github.com/sqlc-dev/pqtype"
)

type GameServerAnalytic struct {
	ServerIp      pqtype.Inet `json:"server_ip"`
	GamesCreated  int64       `json:"games_created"`
	RematchCalled int64       `json:"rematch_called"`
	LastUpdated   time.Time   `json:"last_updated"`
}
