// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"time"

	"github.com/sqlc-dev/pqtype"
)

type ServerHitCount struct {
	ServerIp    pqtype.Inet `json:"server_ip"`
	HitCount    int64       `json:"hit_count"`
	LastUpdated time.Time   `json:"last_updated"`
}
