// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"context"

	"github.com/sqlc-dev/pqtype"
)

type Querier interface {
	AnalyticsGetGamesCreatedCount(ctx context.Context, serverIp pqtype.Inet) (int64, error)
	AnalyticsGetRematchCalledCount(ctx context.Context, serverIp pqtype.Inet) (int64, error)
	AnalyticsIncrementGamesCreatedCount(ctx context.Context, serverIp pqtype.Inet) error
	AnalyticsIncrementRematchCalledCount(ctx context.Context, serverIp pqtype.Inet) error
}

var _ Querier = (*Queries)(nil)
