// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"context"

	"github.com/sqlc-dev/pqtype"
)

type Querier interface {
	GetGamesCreatedCount(ctx context.Context, serverIp pqtype.Inet) (int64, error)
	GetRematchCalledCount(ctx context.Context, serverIp pqtype.Inet) (int64, error)
	IncrementGamesCreatedCount(ctx context.Context, serverIp pqtype.Inet) error
	IncrementRematchCalledCount(ctx context.Context, serverIp pqtype.Inet) error
}

var _ Querier = (*Queries)(nil)
